repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Latest stable version
    hooks:
      - id: black
        name: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0  # Latest stable version
    hooks:
      - id: isort
        name: isort
        language_version: python3

  - repo: https://gitlab.com/pycqa/flake8
    rev: 6.1.0  # Latest stable version
    hooks:
      - id: flake8
        name: flake8
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # Latest stable version
    hooks:
      - id: mypy
        name: mypy
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Latest stable version
    hooks:
      - id: pre-commit-hooks
        name: pre-commit
        language_version: python3
